version: "3.7"
services:

  blog:
    # image: klakegg/hugo:0.83.1-ext-alpine
    image: hugomods/hugo:0.120.4
    ports:
     - "1313:1313"
    networks:
      default:
    volumes:
      - ./:/src
    command: ["hugo", "server", "--disableFastRender", "--bind", "0.0.0.0"]

networks:
  default:
